### ISSUE TITLE
Add python ure_logger bindings

### ISSUE THREAD

**Issue by ngeiswei** [opencog/ure#86]
Python bindings for the ure_logger

https://github.com/opencog/ure/blob/master/opencog/ure/URELogger.h

are still missing. This makes working with the URE with a python a bit cumbersome.

I don't know the python bindings code too well but it seems to enable one need to

1. Have the python logger binding accept any logger, not just opencog's default one.
2. Introduce ure logger function helpers.

for both items can the scheme bindings can be used as exemplar, see

https://github.com/opencog/ure/blob/6444f8a37509b2d0ee7105e5997a8659a5e9e3cf/opencog/scm/opencog/ure/ure-utils.scm#L765-L907
https://github.com/opencog/ure/blob/6444f8a37509b2d0ee7105e5997a8659a5e9e3cf/opencog/ure/URESCM.cc#L117-L118

**Comment by chandramoulirajagopalan** [comment]
I will take up this issue and create a python bindings for this,

**Comment by ngeiswei** [comment]
Thanks!

**Comment by ngeiswei** [comment]
@chandramoulirajagopalan, FYI, unless you have some code nearly ready to be merged, @AmeBel is gonna take it over, it's because he is reasonably familiar with python bindings and we're gonna need this soon.

**Comment by chandramoulirajagopalan** [comment]
I'm working on the code for this right now, Give me some time and I will
fix it in 3 days.

**Comment by AmeBel** [comment]
completed by https://github.com/opencog/ure/pull/107
